[package]
name = "vyom"
version = "0.1.0"
edition = "2024"

[dependencies]
jiff = "0.2.15"
sha2 = "0.10.9"
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = ["fs", "io-std", "io-util", "macros", "rt", "rt-multi-thread"] }
